### ISSUE TITLE
Inquiry About Dataset Used

### ISSUE THREAD

**Issue by alloydas** [gunarakulangunaretnam/human-elephant-conflict-mitigation-system#2]
Hi,

First off, I just want to say - amazing work! I've been exploring your repository, and I'm really impressed by what you've achieved. 

I'm particularly interested in the dataset you've used for this project. Could you share more details about it? If it's available publicly, I'd love to check it out for some research I'm working on animal detection. Any guidelines or conditions for its use would also be super helpful!

Thanks so much for your contribution to the community, and I'm looking forward to any info you can provide about the dataset!

**Comment by gunarakulangunaretnam** [comment]
@alloydas 

Thanks for your appreciation and question!!

Her, you can access Sri Lanka's Element Dataset, containing 10,000 images, at https://www.kaggle.com/datasets/gunarakulangr/sri-lankan-wild-elephant-dataset.
