### ISSUE TITLE
Is it possible to provide the dataset

### ISSUE THREAD

**Issue by kvAkash-512** [gunarakulangunaretnam/human-elephant-conflict-mitigation-system#4]
Amazing work

Could you provide the dataset used

**Comment by gunarakulangunaretnam** [comment]
@kvAkash-512 

Thanks for your appreciation and question!!

Here, you can access Sri Lanka's Element Dataset, containing 10,000 images, at https://www.kaggle.com/datasets/gunarakulangr/sri-lankan-wild-elephant-dataset.
